export const BULLET_INTERVAL_TIME = 200;
export const BULLET_MAX_DISTANCE_FROM_SHIP = 2000;
export const PLANET_INTERVAL_TIME = 2000;
export const PLANET_MAX_DISTANCE_FROM_SHIP = 2000;
export const COLLECTIBLE_INTERVAL_TIME = 5000;
export const COLLECTIBLE_MAX_DISTANCE_FROM_SHIP = 1000;
export const SPHERE_SPHERE_COLLISION = "sphereToSphere";
export const ENTITY_SHIP_COLLISION= "entityToShip";
